### ISSUE TITLE
TF-serving integration with kafka (real-time searving)

### ISSUE THREAD

**Issue by aym-frikha** [juju-solutions/charm-tf-serving#6]
Hello,

Actually, the charm doesn't have the capability to integrate with Kafka for real-time streaming capability.
Tensorflow seem to have the capability to integrate with Kafka and I think it's a useful functionality that we can add to the charm:

https://dimensionless.in/real-time-data-streaming-with-kafka-and-tensorflow/

**Comment by knkski** [comment]
Closing this as I believe you got tf serving and kafka integrated. Feel free to re-open if that's not true
